In [2]:
import glob
import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential

CATEGORIES = ["Eating", "Drinking", "Pregnant"]

def prepare(filepath):
    IMG_SIZE = 200  
    img_array = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 1)


model = tf.keras.models.load_model("CNN.model")

for img in glob.glob("Testing/*.jpg"):
    n= cv2.imread(img)
    

    prediction = model.predict([prepare(img)])
    print(prediction)  # will be a list in a list.

    MaxPosition=np.argmax(prediction)  
    prediction_label= CATEGORIES[MaxPosition]
    print(prediction_label)
   
    
    cv2.namedWindow("output", cv2.WINDOW_NORMAL)
    
    ims = cv2.resize(n, (400, 200))
    cv2.putText(ims, "The camel is " + prediction_label , (20, 100), cv2.FONT_HERSHEY_SIMPLEX, 1,
                    (0, 0, 255), 2)
    cv2.imshow('output', ims)
    
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

[[0. 1. 0.]]
Drinking
[[0. 1. 0.]]
Drinking
[[0. 1. 0.]]
Drinking
[[1. 0. 0.]]
Eating
[[1. 0. 0.]]
Eating
[[1. 0. 0.]]
Eating
[[1.0659901e-22 0.0000000e+00 1.0000000e+00]]
Pregnant
[[0. 0. 1.]]
Pregnant
[[0. 0. 1.]]
Pregnant
